- name: Demo on loops
  hosts: all
  tasks:
    - name: Print fruit name
      debug:
        msg: Fruit name is {{ item }}
      loop:
        - apple
        - banana
        - orange
        - grapes
    - name: Print Fruit name & Quantity
      debug:
        msg: Fruit name is {{ item.name }} & Quantity is {{ item.quantity }}
      loop:
         - { name: "Sweet lime", quantity: 1111 }
         - { name: "Dragan fruit", quantity: 2222 }
         - { name: "Strawberry", quantity: 3333 }
         - { name: "Papaya", quantity: 4444 }
