- name: Demo on Conditions in Ansible
  hosts: localhost
  connection: local
  vars:
    fruit_Name: banana
    a: 200
    b: false
  tasks:
    - name: string condition
      debug:
        msg: Fruit name is banana
      when: fruit_Name == "banana"
    - name: Numerical condition
      debug:
        msg: a is greater than 10
      when: a > 10
    - name: boolean condition
      debug:
        msg: b is true
      when: b




