- name: Demo on Conditions in Ansible
  hosts: localhost
  connection: local
  vars:
    fruit_Name: Apple
    b: 200
  tasks:
    - name: string condition
      debug:
        msg: Fruit name is banana
      when: fruit_Name == "banana"



