- name: Demo on Conditions in Ansible
  hosts: localhost
  vars:
    a: 100
    b: 200
  tasks:
    - name: string condition
      debug:
        msg: Fruit name is banana
      when: fruit_Name == "banana"



